<!--

    Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Distribution License v. 1.0, which is available at
    http://www.eclipse.org/org/documents/edl-v10.php.

    SPDX-License-Identifier: BSD-3-Clause

-->

"<center><table width="95%">\
    <tr><td valign="top" width="25%"><p>&nbsp;</p><p><b>Site Menu</b></p>
	    <sun:hyperlink url="http://maps.google.com" text="Goto Google Maps" />
"	</td>\
	<td width="75%">\
	    <center><h2> Welcome to the Test App! </h2></center>
	<!-- Content goes here -->
